controller_manager:
  ros__parameters:
    update_rate: 50

diff_cont:
  type: diff_drive_controller/DiffDriveController
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.3
    wheel_radius: 0.05
    publish_rate: 50.0
    base_frame_id: base_link
    enable_odom_tf: true
    cmd_vel_timeout: 0.25
    use_stamped_vel: false
    
left_wheel_names: ["left_wheel_joint"]
right_wheel_names: ["right_wheel_joint"]

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
